services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    pull_policy: always
    restart: unless-stopped
    environment:
      - "WEBUI_SECRET_KEY="
    ports:
      - ${WEBUI_PORT:-3000}:8080
    volumes:
      - ${WEBUI_DATA_DIR:-.data/open-webui}:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    ulimits:
      # increase these if embeddings fail with too many open files
      # OR
      # set concurrent connection limit under Admin Panel > Settings > Documents
      nofile:
        soft: 8192
        hard: 65535

volumes:
  open-webui: {}
